Add support for RSMods `Disable Song Previews` Mod
kokolihapihvi/RockSnifferLib pull request #9
Opened 2021-12-11 19:36 UTC by ffio1

Rocksniffer looks for the "_Preview" suffix on the song previews to get the SongKey for the song. To disable song previews, RSMods changes this Wwise event to "Play_{SongKey}_Invalid" so Wwise doesn't know what event to play.

This will allow Rocksniffer to work while the `Disable Song Previews` mod is enabled.

2021-12-13 10:34 UTC, kokolihapihvi requested changes

2021-12-13 10:34 UTC, kokolihapihvi commented on RSHelpers/RSMemoryReader.cs
> +                //Verify Play_ prefix and _Preview or _Invalid suffix
I would like a comment to briefly explain that _Invalid is a RSMod replacement to avoid possible future head scratching.

2021-12-14 00:51 UTC, ffio1 commented
I submitted a new commit that has two comments explaining what the "_Invalid" suffix means, and why we need to look for it.

2021-12-14 07:58 UTC, kokolihapihvi approved these changes

2021-12-14 08:01 UTC, merged

2021-12-14 08:01 UTC, kokolihapihvi commented
Thank you!